# Generated by Django 5.0.7 on 2024-08-08 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookAPI', '0006_alter_menuitem_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='category_title',
            field=models.IntegerField(default=1),
        ),
    ]
