# Generated by Django 5.0.7 on 2024-08-08 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BookAPI', '0007_menuitem_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuitem',
            name='category_title',
        ),
    ]
