# Generated by Django 5.0.7 on 2024-08-12 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BookAPI", "0009_cartitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cartitem",
            name="category",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="inventory",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="name",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="price",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="item",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="BookAPI.menuitem",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
