# Generated by Django 5.0.7 on 2024-08-12 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("BookAPI", "0012_remove_order_order_order_items"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="crewmember",
            new_name="delivery_person",
        ),
    ]
