# Generated by Django 5.0.7 on 2024-08-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BookAPI", "0015_order_sent_by_alter_order_delivery_person"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="items",
        ),
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
