# Generated by Django 5.0.7 on 2024-08-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BookAPI", "0016_remove_order_items_order_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="items",
            field=models.CharField(default=1, max_length=255),
        ),
    ]
