# Generated by Django 5.0.7 on 2024-08-12 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BookAPI", "0017_alter_order_items"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="items",
        ),
        migrations.AddField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(to="BookAPI.cartitem"),
        ),
    ]
