# Generated by Django 5.0.7 on 2024-08-13 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BookAPI", "0018_remove_order_items_order_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivered",
            field=models.BooleanField(default=False),
        ),
    ]
