# Generated by Django 5.0.7 on 2024-08-13 06:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BookAPI", "0019_order_delivered"),
    ]

    operations = [
        migrations.CreateModel(
            name="ItemOfTheDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="BookAPI.menuitem",
                    ),
                ),
            ],
        ),
    ]
